---
- name: include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: include variables when have to use Chrony
  include_vars: "chrony.yml"
  when: (ansible_distribution_major_version|int >= 8 and ansible_os_family == 'RedHat') or ntp_use_chrony

- name: set the correct timezone.
  file:
    src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
    dest: /etc/localtime
    state: link
    force: yes

# Debian family OSes also have an /etc/timezone file.
- name: set timezone in /etc/timezone file.
  template:
    src: timezone.j2
    dest: /etc/timezone
    force: yes
  when: ansible_os_family == 'Debian'

- name: install NTP
  package:
    name: '{{ ntp_package }}'
    state: installed
  notify: restart ntp

- name: generate ntp.conf file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp
  when: ntp_manage_config and not ntp_use_chrony

- name: generate chrony.conf file
  template: src=chrony.conf.j2 dest=/etc/chrony.conf
  notify: restart ntp
  when: ntp_manage_config and ntp_use_chrony

- name: ensure NTP is stopped and disabled as configured.
  service:
    name: '{{ ntp_daemon }}'
    state: stopped
    enabled: no
  when: not ntp_enabled
